### ISSUE TITLE
Criação do tutorial inicial do app

### ISSUE THREAD

**Issue by pedroeagle** [GCES-Escola-em-Casa-2020-2/wiki#2]
**Descrição**
Criar um tutorial que explique cada funcionalidade do aplicativo. Atualmente existe um PR que não está passando no Travis, analisar o motivo e tentar corrigir para que seja aprovado.

**Objetivo**
Ter um tutorial que explique a principais funcionalidades do aplicativo.

**Tarefas**:
- [x] Analisar solução do PR
- [x] Tentar solucionar o problema do Travis
- [x] Se a solução do PR não for coerente com essa issue, implementar por completo

**Checklist**
- [x] O PR foi testado
- [x] O problema do PR foi identificado
- [x] A implementação foi aceita ou criada

**Comment by pedroeagle** [comment]
O problema do Travis é comum a todos os PRs visto que estes não tem acesso as variáveis de ambiente. PR criado documentando o problema no repositório oficial: [PR54](https://github.com/Escola-em-Casa/android-escola-em-casa/pull/54)

**Comment by GeiseSaunier** [comment]
Tentamos resolver o problema hoje no nosso próprio repositório, mas não teve muito sucesso. Identificamos o erro, mas ainda não o solucionamos.
